# Pretest Agialdi Dosinanda
## Use Case (16 October 2019)

In [2]:
import pandas as pd
import numpy as np

In [4]:
churn = pd.read_csv("D:\DATA SCIENCE ACADEMY\Pre Test\churn.csv", encoding='latin1')
churn.head()

,state,account_length,area_code,phone_number,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,...,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,class
0,16,128,415,2845,0,1,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,35,107,415,2301,0,1,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,31,137,415,1616,0,0,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,35,84,408,2510,1,0,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,36,75,415,155,1,0,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

In [6]:
churn.describe()

,state,account_length,area_code,phone_number,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,...,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,class
count,5000.00000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,25.99840,100.25860,436.911400,2499.500000,0.094600,0.264600,7.755200,180.288900,100.029400,30.649668,...,100.191000,17.054322,200.391620,99.919200,9.017732,10.261780,4.435200,2.771196,1.570400,0.141400
std,14.80348,39.69456,42.209182,1443.520003,0.292691,0.441164,13.546393,53.894699,19.831197,9.162069,...,19.826496,4.296843,50.527789,19.958686,2.273763,2.761396,2.456788,0.745514,1.306363,0.348469
min,0.00000,1.00000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,13.00000,73.00000,408.000000,1249.750000,0.000000,0.000000,0.000000,143.700000,87.000000,24.430000,...,87.000000,14.140000,166.900000,87.000000,7.510000,8.500000,3.000000,2.300000,1.000000,0.000000
50%,26.00000,100.00000,415.000000,2499.500000,0.000000,0.000000,0.000000,180.100000,100.000000,30.620000,...,100.000000,17.090000,200.400000,100.000000,9.020000,10.300000,4.000000,2.780000,1.000000,0.000000
75%,39.00000,127.00000,415.000000,3749.250000,0.000000,1.000000,17.000000,216.200000,113.000000,36.750000,...,114.000000,19.900000,234.700000,113.000000,10.560000,12.000000,6.000000,3.240000,2.000000,0.000000
max,50.00000,243.00000,510.000000,4999.000000,1.000000,1.000000,52.000000,351.500000,165.000000,59.760000,...,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000,1.000000

In [19]:
# Insight(1) Info mengenai jumlah pelanggan yang churn dan tidak churn
churn['class'].value_counts()

0    4293
1     707
Name: class, dtype: int64

In [43]:
# Insight(2) Info mengenai state (negara bagian) mana yg mempunyai populasi churn dan stay terbanyak
data1 = churn[['state', 'class']]
xf = data1.sort_values('class',ascending=False)
state1 = xf['class'] == 1
state0 = xf['class'] == 0
print("State paling banyak churn")
print(xf[state1].mode())
print("State paling banyak stay")
print(xf[state0].mode())

State paling banyak churn
   state  class
0     31      1
State paling banyak stay
   state  class
0     49      0

In [47]:
# Insight(3) Info mengenai profiling pelanggan churn dan stay dari parameter International Plan
data2 = churn[['international_plan', 'total_intl_minutes', 'total_intl_calls', 'total_intl_charge', 'class']]
yf = data2.sort_values('class',ascending=False)
state11 = yf['class'] == 1
state00 = yf['class'] == 0
print("analisa mode parameter international plan status churn")
print(yf[state11].mode())
print("analisa mean parameter international plan status churn")
print(yf[state11].mean())
print("analisa std parameter international plan status churn")
print(yf[state11].std())
print("analisa mode parameter international plan status stay")
print(yf[state00].mode())
print("analisa mean parameter international plan status stay")
print(yf[state00].mean())
print("analisa std parameter international plan status stay")
print(yf[state00].std())

analisa mode parameter international plan status churn
   international_plan  total_intl_minutes  total_intl_calls  \
0                   0                11.0                 2

   total_intl_charge  class
0               2.97      1
analisa mean parameter international plan status churn
international_plan     0.281471
total_intl_minutes    10.692362
total_intl_calls       4.151344
total_intl_charge      2.887426
class                  1.000000
dtype: float64
analisa std parameter international plan status churn
international_plan    0.450035
total_intl_minutes    2.793187
total_intl_calls      2.550011
total_intl_charge     0.754057
class                 0.000000
dtype: float64
analisa mode parameter international plan status stay
   international_plan  total_intl_minutes  total_intl_calls  \
0                   0                 9.8                 3

   total_intl_charge  class
0               2.65      0
analisa mean parameter international plan status stay
international_plan     0.063825
total_intl_minutes    10.190869
total_intl_calls       4.481947
total_intl_charge      2.752055
class                  0.000000
dtype: float64
analisa std parameter international plan status stay
international_plan    0.244469
total_intl_minutes    2.749994
total_intl_calls      2.438233
total_intl_charge     0.742443
class                 0.000000
dtype: float64

In [51]:
# Insight(4) Info mengenai profiling pelanggan churn dan stay dari parameter paket Day
data3 = churn[['total_day_minutes', 'total_day_calls', 'total_day_charge', 'class']]
zf = data3.sort_values('class',ascending=False)
state111 = zf['class'] == 1
state000 = zf['class'] == 0
print("analisa mode parameter day usage status churn")
print(zf[state111].mode())
print("analisa mean parameter day usage status churn")
print(zf[state111].mean())
print("analisa std parameter day usage status churn")
print(zf[state111].std())
print("analisa mode parameter day usage status stay")
print(zf[state000].mode())
print("analisa mean parameter day usage status stay")
print(zf[state000].mean())
print("analisa std parameter day usage status stay")
print(zf[state000].std())

analisa mode parameter day usage status churn
   total_day_minutes  total_day_calls  total_day_charge  class
0              160.6            106.0             27.30    1.0
1              176.9              NaN             30.07    NaN
2              225.9              NaN             38.40    NaN
3              248.7              NaN             42.28    NaN
4              255.1              NaN             43.37    NaN
5              267.9              NaN             45.54    NaN
6              273.8              NaN             46.55    NaN
7              287.1              NaN             48.81    NaN
analisa mean parameter day usage status churn
total_day_minutes    207.870580
total_day_calls      100.817539
total_day_charge      35.338416
class                  1.000000
dtype: float64
analisa std parameter day usage status churn
total_day_minutes    68.576475
total_day_calls      20.757110
total_day_charge     11.658195
class                 0.000000
dtype: float64
analisa mode parameter day usage status stay
   total_day_minutes  total_day_calls  total_day_charge  class
0              189.3              102             32.18    0.0
1                NaN              105               NaN    NaN
analisa mean parameter day usage status stay
total_day_minutes    175.746564
total_day_calls       99.899604
total_day_charge      29.877494
class                  0.000000
dtype: float64
analisa std parameter day usage status stay
total_day_minutes    49.634575
total_day_calls      19.674019
total_day_charge      8.437810
class                 0.000000
dtype: float64

In [52]:
# Insight(5) Info mengenai profiling pelanggan churn dan stay dari parameter voice_mail & cust_service
data4 = churn[['voice_mail_plan', 'number_customer_service_calls', 'class']]
bf = data4.sort_values('class',ascending=False)
state1111 = zf['class'] == 1
state0000 = zf['class'] == 0
print("analisa mode parameter voice_mail & cust_service status churn")
print(bf[state1111].mode())
print("analisa mean parameter voice_mail & cust_service status churn")
print(bf[state1111].mean())
print("analisa std parameter voice_mail & cust_service status churn")
print(bf[state1111].std())
print("analisa mode parameter voice_mail & cust_service status stay")
print(bf[state0000].mode())
print("analisa mean parameter voice_mail & cust_service status stay")
print(bf[state0000].mean())
print("analisa std parameter voice_mail & cust_service status stay")
print(bf[state0000].std())

analisa mode parameter voice_mail & cust_service status churn
   voice_mail_plan  number_customer_service_calls  class
0                0                              1      1
analisa mean parameter voice_mail & cust_service status churn
voice_mail_plan                  0.144272
number_customer_service_calls    2.254597
class                            1.000000
dtype: float64
analisa std parameter voice_mail & cust_service status churn
voice_mail_plan                  0.351614
number_customer_service_calls    1.815956
class                            0.000000
dtype: float64
analisa mode parameter voice_mail & cust_service status stay
   voice_mail_plan  number_customer_service_calls  class
0                0                              1      0
analisa mean parameter voice_mail & cust_service status stay
voice_mail_plan                  0.284416
number_customer_service_calls    1.457722
class                            0.000000
dtype: float64
analisa std parameter voice_mail & cust_service status stay
voice_mail_plan                  0.451189
number_customer_service_calls    1.164236
class                            0.000000
dtype: float64